server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yu-judge?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 200010281214
  redis:
    port: 6379
    host: localhost
    database: 0

authorization:
  expired-in: 14400
  secret-key: secret