judge-server-exceptions:
  codes:
    00000: 一切正常
    A0001: 用户错误
    A0002: 注册信息不完整
    A0003: token不存在
    A0004: token无效
    A0005: GET请求参数为空
    A0006: POST请求参数为空
    A0007: 不合法的权限名称
    A0008: 错误的时间格式
    A0009: 无效的URL
    A0010: 无效的端口号
    B0001: 服务器错误
    B0002: 找不到对应Problem
    B0003: 找不到对应solution
    B0004: 语言不在允许的范围内
    B0005: 找不到对应submission
    B0006: 用户不存在
    B0007: 用户名或者密码错误
    B0008: 该用户已经存在
    B0009: 验证码错误
    B0010: 找不到对应用户
    B0011: 找不到对应题目集
    B0012: 题目集中不存在这个问题
    B0013: 找不到目标判题机
    B0014: 这个判题机IP已经存在