judge-server-exceptions:
  codes:
    00000: 一切正常
    A0001: 用户错误
    A0002: 注册信息不完整
    B0001: 服务器错误
    B0002: 找不到对应Problem
    B0003: 找不到对应solution
    B0004: 语言不在允许的范围内
    B0005: 找不到对应submission
    B0006: 用户名不存在
    B0007: 用户名或者密码错误
    B0008: 该用户已经存在