spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  data:
    redis:
      repositories:
        enabled: false
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true