spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true